import fs from 'fs'

const offsets0 = [
  ['kdlsym_addr__mtx_lock_flags', '2eeeb0'],
  ['kdlsym_addr__mtx_lock_sleep', '2eef50'],
  ['kdlsym_addr__mtx_lock_spin_flags', '2ef2d0'],
  ['kdlsym_addr__mtx_unlock_flags', '2ef170'],
  ['kdlsym_addr__mtx_unlock_sleep', '2ef270'],
  ['kdlsym_addr__mtx_unlock_spin_flags', '2ef4a0'],
  ['kdlsym_addr__sceSblAuthMgrGetSelfInfo', '6441e0'],
  ['kdlsym_addr__sceSblAuthMgrSmStart', '63fee0'],
  ['kdlsym_addr__sx_init_flags', '43e390'],
  ['kdlsym_addr__sx_slock', '43e1a0'],
  ['kdlsym_addr__sx_sunlock', '43e710'],
  ['kdlsym_addr__sx_xlock', '43e610'],
  ['kdlsym_addr__sx_xunlock', '43e7d0'],
  ['kdlsym_addr__thread_lock_flags', '2ef610'],
  ['kdlsym_addr__vm_map_lock_read', '7bb80'],
  ['kdlsym_addr__vm_map_unlock_read', '7bbd0'],
  ['kdlsym_addr_AesCbcCfb128Decrypt', '1ff500'],
  ['kdlsym_addr_AesCbcCfb128Encrypt', '1ff2d0'],
  ['kdlsym_addr_allproc', '1b946e0'],
  ['kdlsym_addr_allproc_lock', '1b94680'],
  ['kdlsym_addr_avcontrol_sleep', '6eae30'],
  ['kdlsym_addr_cloneuio', '44e7e0'],
  ['kdlsym_addr_console_cdev', '21f1128'],
  ['kdlsym_addr_console_write', '2d6eb0'],
  ['kdlsym_addr_contigfree', '270bb0'],
  ['kdlsym_addr_contigmalloc', '270810'],
  ['kdlsym_addr_copyin', '2716a0'],
  ['kdlsym_addr_copyinstr', '271b50'],
  ['kdlsym_addr_copyout', '2715b0'],
  ['kdlsym_addr_critical_enter', '2c1980'],
  ['kdlsym_addr_critical_exit', '2c19a0'],
  ['kdlsym_addr_deci_tty_write', '48cde0'],
  ['kdlsym_addr_destroy_dev', '1efab0'],
  ['kdlsym_addr_dmem_start_app_process', '116b60'],
  ['kdlsym_addr_dynlib_do_dlsym', '21f1e0'],
  ['kdlsym_addr_dynlib_find_obj_by_handle', '220360'],
  ['kdlsym_addr_eventhandler_deregister', 'f8700'],
  ['kdlsym_addr_eventhandler_find_list', 'f88f0'],
  ['kdlsym_addr_eventhandler_register', 'f8370'],
  ['kdlsym_addr_exec_new_vmspace', '50e60'],
  ['kdlsym_addr_faultin', '1d4910'],
  ['kdlsym_addr_fget_unlocked', '45d170'],
  ['kdlsym_addr_fpu_kern_ctx', '26541c0'],
  ['kdlsym_addr_fpu_kern_enter', '2196d0'],
  ['kdlsym_addr_fpu_kern_leave', '219790'],
  ['kdlsym_addr_free', '301ce0'],
  ['kdlsym_addr_gdt', '21fb280'],
  ['kdlsym_addr_gpu_va_page_list', '2646ca8'],
  ['kdlsym_addr_icc_nvs_read', '10b310'],
  ['kdlsym_addr_kern_close', '45aac0'],
  ['kdlsym_addr_kern_ioctl', '44fa80'],
  ['kdlsym_addr_kern_mkdirat', '1df080'],
  ['kdlsym_addr_kern_open', '1d9ee0'],
  ['kdlsym_addr_kern_openat', '1d9f40'],
  ['kdlsym_addr_kern_readv', '44f350'],
  ['kdlsym_addr_kern_reboot', '29a380'],
  ['kdlsym_addr_kern_sysents', '1100310'],
  ['kdlsym_addr_kern_thr_create', '1ed670'],
  ['kdlsym_addr_kernel_map', '2268d48'],
  ['kdlsym_addr_kernel_mount', '4df50'],
  ['kdlsym_addr_killproc', '29780'],
  ['kdlsym_addr_kmem_alloc', '37be70'],
  ['kdlsym_addr_kmem_free', '37c040'],
  ['kdlsym_addr_kproc_create', '969e0'],
  ['kdlsym_addr_kproc_exit', '96c50'],
  ['kdlsym_addr_kthread_add', '96f40'],
  ['kdlsym_addr_kthread_exit', '97230'],
  ['kdlsym_addr_M_IOV', '1a792c0'],
  ['kdlsym_addr_M_LINKER', '155c2d0'],
  ['kdlsym_addr_M_MOUNT', '15279f0'],
  ['kdlsym_addr_M_TEMP', '15621e0'],
  ['kdlsym_addr_make_dev_p', '1ef590'],
  ['kdlsym_addr_malloc', '301b20'],
  ['kdlsym_addr_memcmp', '271e20'],
  ['kdlsym_addr_memcpy', '2714b0'],
  ['kdlsym_addr_memmove', 'af850'],
  ['kdlsym_addr_memset', '1496c0'],
  ['kdlsym_addr_mini_syscore_self_binary', '1579df8'],
  ['kdlsym_addr_mount_arg', '4dcc0'],
  ['kdlsym_addr_mount_argb', '4d460'],
  ['kdlsym_addr_mount_argf', '4ddb0'],
  ['kdlsym_addr_mtx_destroy', '2ef9d0'],
  ['kdlsym_addr_mtx_init', '2ef960'],
  ['kdlsym_addr_mtx_lock_sleep', '2eef50'],
  ['kdlsym_addr_mtx_unlock_sleep', '2ef270'],
  ['kdlsym_addr_name_to_nids', '21f4c0'],
  ['kdlsym_addr_pause', '453ea0'],
  ['kdlsym_addr_pfind', '178960'],
  ['kdlsym_addr_pmap_activate', '138940'],
  ['kdlsym_addr_printf', 'b7a30'],
  ['kdlsym_addr_prison0', '111f870'],
  ['kdlsym_addr_proc0', '1b90e00'],
  ['kdlsym_addr_proc_reparent', '173e90'],
  ['kdlsym_addr_proc_rwmem', '41eb00'],
  ['kdlsym_addr_realloc', '301de0'],
  ['kdlsym_addr_rootvnode', '21eff20'],
  ['kdlsym_addr_RsaesPkcs1v15Dec2048CRT', '4628b0'],
  ['kdlsym_addr_sbl_eap_internal_partition_key', '26c4c90'],
  ['kdlsym_addr_sbl_keymgr_buf_gva', '264c808'],
  ['kdlsym_addr_sbl_keymgr_buf_va', '264c000'],
  ['kdlsym_addr_sbl_keymgr_key_rbtree', '2648248'],
  ['kdlsym_addr_sbl_keymgr_key_slots', '2648238'],
  ['kdlsym_addr_sbl_pfs_sx', '264db40'],
  ['kdlsym_addr_sbl_drv_msg_mtx', '2646cb0'],
  ['kdlsym_addr_sceSblACMgrGetPathId', '8bcd0'],
  ['kdlsym_addr_sceSblAuthMgrIsLoadable2', '6439a0'],
  ['kdlsym_addr_sceSblAuthMgrSmVerifyHeader', '641c60'],
  ['kdlsym_addr_sceSblAuthMgrVerifyHeader', '643a00'],
  ['kdlsym_addr_sceSblDriverSendMsg', '61ced0'],
  ['kdlsym_addr_sceSblGetEAPInternalPartitionKey', '61dc10'],
  ['kdlsym_addr_sceSblKeymgrClearKey', '61f9d0'],
  ['kdlsym_addr_sceSblKeymgrSetKeyForPfs', '61f690'],
  ['kdlsym_addr_sceSblKeymgrSetKeyStorage', '624970'],
  ['kdlsym_addr_sceSblKeymgrSmCallfunc', '61f260'],
  ['kdlsym_addr_sceSblPfsSetKeys', '6252d0'],
  ['kdlsym_addr_sceSblRngGetRandomNumber', '6496a0'],
  ['kdlsym_addr_sceSblServiceMailbox', '630c40'],
  ['kdlsym_addr_sched_prio', '1cbb90'],
  ['kdlsym_addr_self_orbis_sysvec', '1528e30'],
  ['kdlsym_addr_Sha256Hmac', '445060'],
  ['kdlsym_addr_snprintf', 'b7d30'],
  ['kdlsym_addr_spinlock_exit', '314780'],
  ['kdlsym_addr_sprintf', 'b7c70'],
  ['kdlsym_addr_sscanf', '26c8d0'],
  ['kdlsym_addr_strcmp', '40e700'],
  ['kdlsym_addr_strdup', '278540'],
  ['kdlsym_addr_strlen', '30f450'],
  ['kdlsym_addr_strncmp', '124750'],
  ['kdlsym_addr_strstr', '487ab0'],
  ['kdlsym_addr_sys_accept', '4488a0'],
  ['kdlsym_addr_sys_bind', '447f30'],
  ['kdlsym_addr_sys_close', '45aab0'],
  ['kdlsym_addr_sys_dup2', '458cb0'],
  ['kdlsym_addr_sys_fstat', '45b030'],
  ['kdlsym_addr_sys_getdents', '1df840'],
  ['kdlsym_addr_sys_kill', '27050'],
  ['kdlsym_addr_sys_listen', '448170'],
  ['kdlsym_addr_sys_lseek', '1dbf10'],
  ['kdlsym_addr_sys_mkdir', '1df000'],
  ['kdlsym_addr_sys_mlock', '166f30'],
  ['kdlsym_addr_sys_mlockall', '166fe0'],
  ['kdlsym_addr_sys_mmap', '165f50'],
  ['kdlsym_addr_sys_munmap', '166660'],
  ['kdlsym_addr_sys_nmount', '4a960'],
  ['kdlsym_addr_sys_open', '1d9ec0'],
  ['kdlsym_addr_sys_ptrace', '41f1a0'],
  ['kdlsym_addr_sys_read', '44ebc0'],
  ['kdlsym_addr_sys_recvfrom', '449b40'],
  ['kdlsym_addr_sys_rmdir', '1df380'],
  ['kdlsym_addr_sys_sendto', '449420'],
  ['kdlsym_addr_sys_setuid', '18e0'],
  ['kdlsym_addr_sys_shutdown', '449d90'],
  ['kdlsym_addr_sys_socket', '447530'],
  ['kdlsym_addr_sys_stat', '1dc4f0'],
  ['kdlsym_addr_sys_unlink', '1db8d0'],
  ['kdlsym_addr_sys_unmount', '4c290'],
  ['kdlsym_addr_sys_wait4', '173fd0'],
  ['kdlsym_addr_sys_write', '44f0d0'],
  ['kdlsym_addr_trap_fatal', '2df710'],
  ['kdlsym_addr_utilUSleep', '65b170'],
  ['kdlsym_addr_vm_fault_disable_pagefaults', '156c70'],
  ['kdlsym_addr_vm_fault_enable_pagefaults', '156ca0'],
  ['kdlsym_addr_vm_map_lookup_entry', '7c1c0'],
  ['kdlsym_addr_vmspace_acquire_ref', '7b9e0'],
  ['kdlsym_addr_vmspace_alloc', '7b550'],
  ['kdlsym_addr_vmspace_free', '7b810'],
  ['kdlsym_addr_vn_fullpath', '2648c0'],
  ['kdlsym_addr_vsnprintf', 'b7dd0'],
  ['kdlsym_addr_wakeup', '453ec0'],
  ['kdlsym_addr_Xfast_syscall', '1c0']
]

const offsets = [
  ['kdlsym_addr_bzero', '2713f0'],
  ['kdlsym_addr_sys_getpid', '271e50'],
  ['kdlsym_addr_sys_sysctl', '2a2e90'],
  ['kdlsym_addr_printf_hook', '1a7ed68'],
  ['kdlsym_addr_sceSblAuthMgrIsLoadable__sceSblACMgrGetPathId_hook', '64473c'],
  ['kdlsym_addr_sceSblAuthMgrIsLoadable2_hook', '64488e'],
  ['kdlsym_addr_sceSblAuthMgrSmLoadSelfBlock__sceSblServiceMailbox_hook', '642f68'],
  ['kdlsym_addr_sceSblAuthMgrSmLoadSelfSegment__sceSblServiceMailbox_hook', '64232d'],
  ['kdlsym_addr_sceSblAuthMgrVerifyHeader_hookA', '645026'],
  ['kdlsym_addr_sceSblAuthMgrVerifyHeader_hookB', '645d09'],
  ['kdlsym_addr_sceSblKeymgrSetKeyStorage__sceSblDriverSendMsg_hook', '624a15'],
  ['kdlsym_addr_sceSblKeymgrInvalidateKey__sx_xlock_hook', '62084d'],
  ['kdlsym_addr_npdrm_decrypt_isolated_rif__sceSblKeymgrSmCallfunc_hook', '64e070'],
  ['kdlsym_addr_npdrm_decrypt_rif_new__sceSblKeymgrSmCallfunc_hook', '64ee3e'],
  ['kdlsym_addr_mountpfs__sceSblPfsSetKeys_hookA', '6c3ef9'],
  ['kdlsym_addr_mountpfs__sceSblPfsSetKeys_hookB', '6c412a'],
  ['kdlsym_addr_sceRegMgrGetInt', '4e9dd0'],
  ['kdlsym_addr_sceRegMgrSetInt', '4e8b10'],
  ['kdlsym_addr_sceRegMgrGetBin', '4ea770'],
  ['kdlsym_addr_sceRegMgrSetBin', '4ea6c0'],
  ['kdlsym_addr_sceRegMgrGetStr', '4ea5f0'],
  ['kdlsym_addr_sceRegMgrSetStr', '4f65b5']
]

const fileContent = fs.readFileSync('offsets.csv', 'utf8')
const lines = fileContent.split('\n')

// const matches: string[] = []

for (const offset of offsets) {
  const match = lines.find(line =>
    line.startsWith(`"false","0x${offset[1]}"`)
  )
  if (match) {
    // matches.push(match)
    const split = match.split('","')
    offset[1] = split[1]
    offset[2] = split[4]
  }
}
// console.log('Matches:', matches.length, 'out of', offsets.length)

let code = ''

for (const offset of offsets) {
  code += `#define ${offset[0]}  ${offset[2] || `0x${offset[1]}`}`
    + `${offset[2] ? '' : ' // missing'}\n`
}

console.log(code)
